### ISSUE TITLE
Checkpoint time parameter needed

### ISSUE THREAD

**Issue by dd1b** [Stjubit/TA-jira_issue_input#7]
This plugin needs a checkpoint time for last update parameter to be used in JQL.

The reason is because in case of Splunk failure there will be lost of collected data if updated parameter is a fixed time interval (e.g update<5m).

It would be good to have a feature to run with updated > last_run #last_run is timestamp of last execution of data retrieval.

As reference can be Splunk DB Connect plugin that has a configurable parameter and (?) can be used for data query.

**Comment by Stjubit** [comment]
Hi 👋
Sorry for the delay.
I totally agree with you that a checkpoint would make more sense than overlapping intervals, but I don't yet know how I should keep this backwards-compatible. I don't want to break something if one just updates the add-on.
I will take a look at the issue this week and will hopefully come up with a good solution.

**Comment by Stjubit** [comment]
I implemented checkpoint support in version `1.1.0`.
You can find the new release on Splunkbase: https://splunkbase.splunk.com/app/6168.
Update notes can be found here: https://github.com/Stjubit/TA-jira_issue_input#update-notes.
